domain_list = ["gmail.com", "outlook.com", "yahoo.com", "hotmail.com", "aol.com", "protonmail.com", "zoho.com", "mail.com", "gmx.com", "icloud.com", "yandex.com", "fastmail.com", "tutanota.com", "mail.ru", "hushmail.com", "airmail.net", "lycos.com", "netcourrier.com", "zimbra.com", "rediffmail.com", "mailinator.com", "freemail.de", "freemail.ru", "email.org", "email.ru", "freeneted.de", "bigpond.com", "verizon.net", "sky.com"]

US_CITIES_BY_STATE = {
    "AL": ["Birmingham", "Montgomery", "Huntsville", "Mobile", "Tuscaloosa"],
    "AK": ["Anchorage", "Fairbanks", "Juneau", "Sitka", "Ketchikan"],
    "AZ": ["Phoenix", "Tucson", "Mesa", "Scottsdale", "Chandler", "Tempe"],
    "AR": ["Little Rock", "Fort Smith", "Fayetteville", "Springdale", "Jonesboro"],
    "CA": ["Los Angeles", "San Francisco", "San Diego", "San Jose", "Sacramento", "Oakland", "Fresno", "Long Beach", "Bakersfield", "Anaheim", "Irvine"],
    "CO": ["Denver", "Colorado Springs", "Aurora", "Boulder", "Fort Collins"],
    "CT": ["Hartford", "New Haven", "Stamford", "Bridgeport", "Waterbury"],
    "DE": ["Wilmington", "Dover", "Newark", "Middletown", "Smyrna"],
    "FL": ["Miami", "Orlando", "Tampa", "Jacksonville", "Fort Lauderdale", "St. Petersburg", "Tallahassee", "Gainesville", "Sarasota"],
    "GA": ["Atlanta", "Savannah", "Augusta", "Columbus", "Macon", "Athens"],
    "HI": ["Honolulu", "Hilo", "Kailua", "Kapolei", "Pearl City"],
    "ID": ["Boise", "Meridian", "Nampa", "Idaho Falls", "Pocatello"],
    "IL": ["Chicago", "Aurora", "Naperville", "Springfield", "Peoria", "Rockford"],
    "IN": ["Indianapolis", "Fort Wayne", "Evansville", "South Bend", "Carmel"],
    "IA": ["Des Moines", "Cedar Rapids", "Davenport", "Sioux City", "Iowa City"],
    "KS": ["Wichita", "Overland Park", "Kansas City", "Topeka", "Olathe"],
    "KY": ["Louisville", "Lexington", "Bowling Green", "Owensboro", "Covington"],
    "LA": ["New Orleans", "Baton Rouge", "Shreveport", "Lafayette", "Lake Charles"],
    "ME": ["Portland", "Lewiston", "Bangor", "Augusta", "Biddeford"],
    "MD": ["Baltimore", "Annapolis", "Rockville", "Frederick", "Gaithersburg"],
    "MA": ["Boston", "Worcester", "Springfield", "Cambridge", "Lowell", "Salem"],
    "MI": ["Detroit", "Grand Rapids", "Ann Arbor", "Lansing", "Flint", "Kalamazoo"],
    "MN": ["Minneapolis", "St. Paul", "Rochester", "Duluth", "Bloomington"],
    "MS": ["Jackson", "Gulfport", "Biloxi", "Hattiesburg", "Meridian"],
    "MO": ["Kansas City", "St. Louis", "Springfield", "Columbia", "Independence"],
    "MT": ["Billings", "Missoula", "Great Falls", "Bozeman", "Helena"],
    "NE": ["Omaha", "Lincoln", "Bellevue", "Grand Island", "Kearney"],
    "NV": ["Las Vegas", "Reno", "Henderson", "North Las Vegas", "Sparks"],
    "NH": ["Manchester", "Nashua", "Concord", "Dover", "Portsmouth"],
    "NJ": ["Newark", "Jersey City", "Trenton", "Princeton", "Atlantic City", "Hoboken"],
    "NM": ["Albuquerque", "Santa Fe", "Las Cruces", "Rio Rancho", "Roswell"],
    "NY": ["New York", "Buffalo", "Rochester", "Albany", "Syracuse", "Yonkers"],
    "NC": ["Charlotte", "Raleigh", "Durham", "Greensboro", "Winston-Salem", "Asheville"],
    "ND": ["Fargo", "Bismarck", "Grand Forks", "Minot", "Williston"],
    "OH": ["Columbus", "Cleveland", "Cincinnati", "Toledo", "Akron", "Dayton"],
    "OK": ["Oklahoma City", "Tulsa", "Norman", "Broken Arrow", "Edmond"],
    "OR": ["Portland", "Salem", "Eugene", "Bend", "Medford", "Corvallis"],
    "PA": ["Philadelphia", "Pittsburgh", "Allentown", "Erie", "Harrisburg", "Lancaster"],
    "RI": ["Providence", "Warwick", "Cranston", "Pawtucket", "Newport"],
    "SC": ["Charleston", "Columbia", "Greenville", "Myrtle Beach", "Spartanburg"],
    "SD": ["Sioux Falls", "Rapid City", "Aberdeen", "Brookings", "Pierre"],
    "TN": ["Nashville", "Memphis", "Knoxville", "Chattanooga", "Clarksville"],
    "TX": ["Houston", "Dallas", "Austin", "San Antonio", "Fort Worth", "El Paso", "Arlington", "Plano", "Corpus Christi", "Lubbock"],
    "UT": ["Salt Lake City", "Provo", "West Valley City", "Ogden", "St. George"],
    "VT": ["Burlington", "Montpelier", "Rutland", "Barre", "Brattleboro"],
    "VA": ["Virginia Beach", "Richmond", "Norfolk", "Arlington", "Alexandria", "Roanoke"],
    "WA": ["Seattle", "Spokane", "Tacoma", "Vancouver", "Bellevue", "Olympia"],
    "WV": ["Charleston", "Huntington", "Morgantown", "Parkersburg", "Wheeling"],
    "WI": ["Milwaukee", "Madison", "Green Bay", "Kenosha", "Racine"],
    "WY": ["Cheyenne", "Casper", "Laramie", "Gillette", "Rock Springs"],
}

# Population weights for each state
STATE_POPULATION_WEIGHTS = {
    "CA": 12, "TX": 10, "FL": 8, "NY": 7, "PA": 5,
    "IL": 5, "OH": 4, "GA": 4, "NC": 4, "MI": 4,
    "NJ": 3, "VA": 3, "WA": 3, "AZ": 3, "MA": 3,
    "TN": 3, "IN": 2, "MO": 2, "MD": 2, "WI": 2,
    "CO": 2, "MN": 2, "SC": 2, "AL": 2, "LA": 2,
    "KY": 2, "OR": 2, "OK": 2, "CT": 1, "UT": 1,
    "IA": 1, "NV": 1, "AR": 1, "MS": 1, "KS": 1,
    "NM": 1, "NE": 1, "ID": 1, "WV": 1, "HI": 1,
    "NH": 1, "ME": 1, "MT": 1, "RI": 1, "DE": 1,
    "SD": 1, "ND": 1, "AK": 1, "VT": 1, "WY": 1,
}